# Generated by Django 5.1.6 on 2025-04-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_instructorpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorpayment',
            name='month',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=4),
        ),
    ]
