# Generated by Django 5.1.6 on 2025-04-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_instructorpayment_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorPayment',
        ),
    ]
