# Generated by Django 5.1.6 on 2025-04-08 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0010_course_is_compleated'),
        ('payment', '0001_initial'),
        ('teacher', '0004_delete_instructorpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_method', models.CharField(max_length=50)),
                ('payout_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.instructor')),
            ],
            options={
                'unique_together': {('instructor', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCourseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_enrollments', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to_instructor', models.BooleanField(default=False)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.instructor')),
            ],
            options={
                'unique_together': {('instructor', 'course', 'month')},
            },
        ),
    ]
