# Generated by Django 5.1.6 on 2025-04-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_instructorpayout_monthlycoursestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycoursestats',
            name='instructor_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlycoursestats',
            name='platform_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
