# Generated by Django 5.1.6 on 2025-04-08 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_monthlycoursestats_instructor_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorpayout',
            name='paid_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
