# Generated by Django 5.1.6 on 2025-03-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0009_coursereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_compleated',
            field=models.BooleanField(default=False),
        ),
    ]
