# Generated by Django 5.1.6 on 2025-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0011_studentcourseprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourseprogress',
            name='total_lessons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
