# Generated by Django 5.1.6 on 2025-04-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0012_studentcourseprogress_total_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourseprogress',
            name='total_lessons',
        ),
    ]
