# Generated by Django 5.1.6 on 2025-04-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcqtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
    ]
